### ISSUE TITLE
404 Not Found on Access Keys Tutorial

### ISSUE THREAD

**Issue by grab-a-byte** [RoguePlanetoid/Tutorialr#3]
I was going through the documents and reading them and the Access Keys Tutorial leads to a 404 not found page. Image attached.
![image](https://user-images.githubusercontent.com/30392071/60623710-32f7a580-9ddb-11e9-8107-2c029ca4035f.png)

**Comment by RoguePlanetoid** [comment]
This URL was fixed during the refresh of tutorialr.com
